### ISSUE TITLE
Not working in a containerized workflow

### ISSUE THREAD

**Issue by twe-syde** [tanmancan/action-setup-ssh-agent-key#1]
Example workflow

```
jobs:
  testing:
    runs-on: self-hosted
    container:
      image: ubuntu:latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install openssh-client
        run: apt update && apt install -y openssh-client

      - uses: tanmancan/action-setup-ssh-agent-key@1.0.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-public-key: "example.com ecdsa-sha2-nistp256 $SOME_KEY"

      - name: test connectivity
        run: ssh -T -l example.com 'ls -la'
        continue-on-error: true
```

This will not work because the container instance get's an altered $HOME environment variable. It points to "/github/home". This is were the know_hosts file will got to. But ssh will look at /root/.ssh/known_hosts.

The hack is to link both directories before hand.

```
      - name: link .ssh dir
        run: ln -s /github/home/.ssh /root/.ssh
```
